#!/bin/bash
echo "RF4 Cafe OCR Training"
echo "====================="
echo ""
echo "Training data prepared in: tesseract_training"
echo ""
echo "To complete training, you need to:"
echo "1. Install tesstrain: git clone https://github.com/tesseract-ocr/tesstrain.git"
echo "2. Run the training script: tesseract_training/run_training.sh"
echo ""
echo "Alternatively, use the pre-processed ground truth files with tesseract directly:"
echo "  - Images: tesseract_training/ground-truth/*.png"
echo "  - Text: tesseract_training/ground-truth/*.gt.txt"
