version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rf4_records_postgres
    env_file: 
      - ./backend/.env.development
    environment:
      - POSTGRES_DB=rf4_records_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local