[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt --break-system-packages",
    "cd frontend && npm ci",
    "chmod -R +x frontend/node_modules/.bin"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "echo 'Build complete'"
]

[start]
cmd = "cd backend && python start_server.py" 